# Generated by Django 4.1.5 on 2023-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='certificates')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('startYear', models.DateField(max_length=4)),
                ('endYear', models.DateField(max_length=4)),
                ('logo', models.ImageField(upload_to='institutesLogos')),
            ],
        ),
    ]
