# Generated by Django 4.1.5 on 2023-03-07 19:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='endYear',
            field=models.IntegerField(validators=[core.validators.validate_year_of_formation]),
        ),
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.FileField(upload_to='institutesLogos', validators=[core.validators.validate_logo]),
        ),
        migrations.AlterField(
            model_name='formation',
            name='startYear',
            field=models.IntegerField(validators=[core.validators.validate_year_of_formation]),
        ),
    ]
