# Generated by Django 4.1.5 on 2023-03-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_formation_endyear_alter_formation_logo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formation',
            new_name='Formations',
        ),
        migrations.RenameField(
            model_name='certificates',
            old_name='picture',
            new_name='pictures',
        ),
        migrations.RenameField(
            model_name='certificates',
            old_name='title',
            new_name='titles',
        ),
        migrations.RenameField(
            model_name='formations',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='formations',
            old_name='institute',
            new_name='institutes',
        ),
        migrations.RenameField(
            model_name='formations',
            old_name='logo',
            new_name='logos',
        ),
    ]
