# Generated by Django 4.1.5 on 2023-03-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_certificates_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='pictures',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='institutes',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='logos',
            new_name='logo',
        ),
    ]
