# Generated by Django 4.1.5 on 2023-03-08 16:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_pictures_certificate_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.FileField(upload_to='static/core/images', validators=[core.validators.validate_logo]),
        ),
    ]
