# Generated by Django 4.1.5 on 2023-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_formation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='picture',
            field=models.ImageField(upload_to='static/core/images'),
        ),
    ]
