# Generated by Django 4.1.5 on 2023-03-08 20:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_certificate_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='static/core/images')),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media_btn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('icon', models.FileField(upload_to='static/core/images/socialMediaIcons', validators=[core.validators.validate_logo])),
            ],
        ),
    ]
