# Generated by Django 4.1.5 on 2023-03-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bio_picture_social_media_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio_picture',
            name='description',
            field=models.CharField(default='Foto', max_length=100),
        ),
    ]
