# Generated by Django 4.1.5 on 2023-03-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bio_picture_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='static/core/images')),
                ('alt', models.CharField(default='Foto de Leonardo Costa', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='bio_picture',
            old_name='description',
            new_name='alt',
        ),
    ]
